services:
  database:
    image: mysql:8.4
    container_name: database1
    networks:
      - nightout-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DATABASENAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    # Memory for database (init from folder:sql-scripts !!!)
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ../backend           # Itt mondjuk meg, hol van a projekt gyökere
      dockerfile: docker-build/Dockerfile.dev  # Itt pedig a fájl pontos helyét és nevét
    container_name: backend1
    networks:
      - nightout-network
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - database
    environment:
      # Application
      SPRING_APPLICATION_NAME: backend

      # Datasource
      SPRING_DATASOURCE_URL: jdbc:mysql://database:${DATABASE_PORT}/${DATABASENAME}?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

      # CORS
      MOESIF_CORS_ALLOW_ORIGINS: "${ALLOW_CORS_ORIGIN}"
      MOESIF_CORS_ALLOW_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      MOESIF_CORS_ALLOW_HEADERS: "Authorization,Content-Type"
      MOESIF_CORS_ALLOW_CREDENTIALS: "true"

      # App-specific
      APP_BASE_URL: ${APP_BASE_URL}

  frontend:  # <--- Ennek pontosan itt kell lennie!
    image: nginx:alpine
    container_name: nightout_frontend
    networks:
      - nightout-network
    ports:
      - "3000:80"
    volumes:
      - ../frontend/app:/usr/share/nginx/html:ro

networks:
  nightout-network:
    driver: bridge